### ISSUE TITLE
RuntimeError: ERROR: 'tuple' object has no attribute 'size' while processing simple.diag

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/seqdiag#12]
**VERSIONS:**

  * seqdiag 0.8.0 (and repository tip)
  * blockdiag 1.2.1 (and repository tip)
  * PIL 1.1.7
  * MACOSX 11.4.2 (Lion)
  * Python 2.7.1

After installation of `blockdiag` and `seqdiag`,
when I run:

    $ cd examples
    $ seqdiag simple.diag

I get the following error message:

    :::console
    ERROR: 'tuple' object has no attribute 'size' 

When I run `seqdiag --debug simple.diag` 
Then I get the following traceback:

    :::console
    Traceback (most recent call last):
    File ".../blockdiag/utils/bootstrap.py", line 35, in run
      return self.build_diagram(parsed)
    ...
    File ".../blockdiag/imagedraw/png.py", line 273, in textsize
      scale=self.scale_ratio, **kwargs)
    File ".../blockdiag/imagedraw/textfolder.py", line 66, in get
      return HorizontalTextFolder(*args, **kwargs)
    File ".../blockdiag/imagedraw/textfolder.py", line 210, in __init__
      self._result = self._lines()
    File ".../blockdiag/imagedraw/textfolder.py", line 284, in _lines
      maxwidth, maxheight = self.box.size
    AttributeError: 'tuple' object has no attribute 'size'

The error is located in `blockdiag` where a tuple w/ 4 params are set to `self.box`.

**NOTE:** When I run the current repository tip of `seqdiag` testsuite, the same error occurs. Because tests/diagrams/ where missing in `seqdiag-0.8.0`, this issue was probably not noticed.

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/seqdiag/issue/12
- Originally reported by: [jenisys](https://bitbucket.org/jenisys)
- Originally created at: 2012-10-28T14:49:05.393

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2011-08-10 11:47:59+00:00_

I fixed it at rev.887

**Comment by tk0miya** [comment]
_From [jenisys](https://bitbucket.org/jenisys) on 2012-10-28 14:59:52+00:00_

The following patch in `blockdiag: ImageDrawExBase.textsize()` fixes the problem for PNG:

    diff -r 78a590e633cc src/blockdiag/imagedraw/png.py
    --- a/src/blockdiag/imagedraw/png.py	Sat Oct 27 17:16:11 2012 +0900
    +++ b/src/blockdiag/imagedraw/png.py	Sun Oct 28 15:46:15 2012 +0100
    @@ -268,7 +268,7 @@
             if maxwidth is None:
                 maxwidth = 65535
     
    -        box = (0, 0, maxwidth, 65535)
    +        box = Box(0, 0, maxwidth, 65535)    # XXX-JE-PATCH: seqdiag issue #12
             textbox = textfolder.get(self, box, string, font,
                                      scale=self.scale_ratio, **kwargs)
             return textbox.outlinebox.size


Additional problems still exist with the current `seqdiag` tip. The testsuite has similar issues with SVG tests (that are not yet fixed).

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2012-10-28 16:17:35+00:00_

Thank you, I fixed and released new version of blockdiag (1.2.2)

**Comment by tk0miya** [comment]
_From [jenisys](https://bitbucket.org/jenisys) on 2012-10-30 20:40:37+00:00_

`blockdiag.imagedraw.pdf` needs the same fix, too.
Currently, only `png` and `svg` are fixed.

**Comment by tk0miya** [comment]
_From [jenisys](https://bitbucket.org/jenisys) on 2012-10-30 20:43:47+00:00_

`pdf` submodule has same issue. Only `png` and `svg` are currently fixed on tip. Therefore, the issue is only partially fixed (but my main issue is resolved now, Thx).

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2012-11-19 15:54:36+00:00_

Thank you, I fixed it again. I missed it
https://bitbucket.org/tk0miya/blockdiag/changeset/2e6afa30edc2972be75fddbb44a09478

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2012-11-19 15:56:33+00:00_

Assign to me (I've never noticed the comment...)
