### ISSUE TITLE
  b ->> A; does not work anymore

### ISSUE THREAD

**Issue by tk0miya** [blockdiag/seqdiag#4]
after upgrading from sphinxcontrib-seqdiag = 0.2.2 to 0.3.2
this does not work anymore:
  b ->> A;

traceback:
wouter@midgard: /opt/buildouts/test-documentation >  cat /tmp/sphinx-err-KbdfUH.log
# Sphinx version: 1.1.3
# Python version: 2.6.8rc1
# Docutils version: 0.8.1 release
# Jinja2 version: 2.6
Traceback (most recent call last):
  File "/opt/buildouts/test-documentation/eggs/Sphinx-1.1.3-py2.6.egg/sphinx/cmdline.py", line 189, in main
    app.build(force_all, filenames)
  File "/opt/buildouts/test-documentation/eggs/Sphinx-1.1.3-py2.6.egg/sphinx/application.py", line 204, in build
    self.builder.build_update()
  File "/opt/buildouts/test-documentation/eggs/Sphinx-1.1.3-py2.6.egg/sphinx/builders/__init__.py", line 196, in build_update
    'out of date' &#37; len(to_build))
  File "/opt/buildouts/test-documentation/eggs/Sphinx-1.1.3-py2.6.egg/sphinx/builders/__init__.py", line 216, in build
    purple, length):
  File "/opt/buildouts/test-documentation/eggs/Sphinx-1.1.3-py2.6.egg/sphinx/builders/__init__.py", line 120, in status_iterator
    for item in iterable:
  File "/opt/buildouts/test-documentation/eggs/Sphinx-1.1.3-py2.6.egg/sphinx/environment.py", line 613, in update_generator
    self.read_doc(docname, app=app)
  File "/opt/buildouts/test-documentation/eggs/Sphinx-1.1.3-py2.6.egg/sphinx/environment.py", line 761, in read_doc
    pub.publish()
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/core.py", line 211, in publish
    self.settings)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/readers/__init__.py", line 69, in read
    self.parse()
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/readers/__init__.py", line 75, in parse
    self.parser.parse(self.input, document)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/__init__.py", line 157, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 2943, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 329, in section
    self.new_subsection(title, lineno, messages)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 398, in new_subsection
    node=section_node, match_titles=1)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 284, in nested_parse
    node=node, match_titles=match_titles)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 2709, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 329, in section
    self.new_subsection(title, lineno, messages)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 398, in new_subsection
    node=section_node, match_titles=1)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 284, in nested_parse
    node=node, match_titles=match_titles)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 2285, in explicit_markup
    self.explicit_list(blank_finish)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 2316, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 321, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/opt/buildouts/eurid-documentatio/neggs/docutils-0.8.1-py2.6.egg/docutils/statemachine.py", line 237, in run
    context, state, transitions)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/statemachine.py", line 458, in check_line
    return method(match, context, next_state)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 2589, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 2295, in explicit_construct
    return method(self, expmatch)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 2036, in directive
    directive_class, match, type_name, option_presets)
  File "/opt/buildouts/test-documentation/eggs/docutils-0.8.1-py2.6.egg/docutils/parsers/rst/states.py", line 2087, in run_directive
    result = directive_instance.run()
  File "/opt/buildouts/test-documentation/eggs/blockdiag-1.1.4-py2.6.egg/blockdiag/utils/rst/directives.py", line 131, in run
    diagram = self.node2diagram(node)
  File "/opt/buildouts/test-documentation/eggs/seqdiag-0.7.3-py2.6.egg/seqdiag/utils/rst/directives.py", line 45, in node2diagram
    tree = parser.parse_string(node['code'])
  File "/opt/buildouts/test-documentation/eggs/seqdiag-0.7.3-py2.6.egg/seqdiag/parser.py", line 207, in parse_string
    raise ParseException(message)
ParseException: Got unexpected token at line 15 column 17

----

updating environment: 56 added, 0 changed, 0 removed
WARNING: fontsize is obsoleted; use default_fontsize                                                                                                                                                                              
ERROR: diagram{

  webservice <<- mongo-db  [label = "Return data"];
  webservice ->> mongo-db  [label = "Fetch data"];

  webservice << gateway  [label = "Return data"];
  webservice ->> gateway  [label = "Fetch data"];

  webservice <<- mysql-db  [label = "Return data"];
  webservice ->> mysql-db  [label = "Fetch data"];

  webservice <<- rt-db  [label = "Return data"];
  webservice ->> rt-db  [label = "Fetch data"];

  webservice <<- -db  [label = "Return data"];
  webservice ->> rt-db  [label = "Fetch data"];
  }

---

using python2.6

----------------------------------------
- Bitbucket: https://bitbucket.org/blockdiag/seqdiag/issue/4
- Originally reported by: Wouter Vanden Hove
- Originally created at: 2012-03-20T00:30:12.683

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2011-02-19 14:18:00+00:00_

What you mean "PNG quaulity"?
Fontsize of labels? Or corner of shapes?

You can change resolution of diagram with diagram attributes::

{{{
{
  node_width = 320;
  node_height = 100;
  span_width = 160;
  span_height = 100;
  fontsize = 24;

  A -> B;
}
}}}

This way gives you more larger images, but it will make you satisfy.
So I want to know your purposes.

**Comment by tk0miya** [comment]
_From Takeshi KOMIYA on 2012-04-22 09:02:24+00:00_

There is some syntax errors on your diagrams.
"<<" should be replace with "<<-" .

But, there is more problem; syntax error in seqdiag make sphinx crashes.
So, I fixed it reports ONLY warnings at sphinxcontrib-seqdiag 0.4.1 .
Please try again with newly versions.

Thanks.

**Comment by tk0miya** [comment]
_From Chad Skeeters on 2013-01-31 01:18:58+00:00_

I tried this, but the lines were too thin at the resolution I wanted, and their seems to be some weirdness with where the text is placed when the fontsize gets pretty large.

As a workaround, I rendered to SVG first and scaled up as I used some other tool to convert to PNG (or PDF in my case).

http://wiki.inkscape.org/wiki/index.php/Tools#svg2pdf
